import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { cn } from "@/utils/utils";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ugang Recker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="flex flex-col" lang="en">
      <Navbar />
      <body className={cn(inter.className, "flex-1")}>{children}</body>
      <Footer />
      <ToastContainer />
    </html>
  );
}
